/* DERIOR — Product Catalog (source of truth for search + cart) */
window.PRODUCTS = [

  /* ─── Living Room ─────────────────────────────────────────── */
  { id: 'linen-three-seater-sofa',  name: 'Linen Three-Seater Sofa',   category: 'Living Room', subcategory: 'Sofa Sets',       price: 2400, priceDisplay: 'From $2,400', image: 'img/LR/S1 (1).webp',   url: 'living-room.html#sofa-sets' },
  { id: 'vintage-velvet-sofa',      name: 'Vintage Velvet Sofa',        category: 'Living Room', subcategory: 'Sofa Sets',       price: 2800, priceDisplay: 'From $2,800', image: 'img/LR/S2 (1).webp',   url: 'living-room.html#sofa-sets' },
  { id: 'boucle-modular-sofa',      name: 'Bouclé Modular Sofa',        category: 'Living Room', subcategory: 'Sofa Sets',       price: 3200, priceDisplay: 'From $3,200', image: 'img/LR/S3 (4).webp',   url: 'living-room.html#sofa-sets' },
  { id: 'deep-comfort-sofa',        name: 'Deep Comfort Sofa',          category: 'Living Room', subcategory: 'Sofa Sets',       price: 2600, priceDisplay: 'From $2,600', image: 'img/LR/S4 (1).webp',   url: 'living-room.html#sofa-sets' },
  { id: 'low-profile-lounge-sofa',  name: 'Low-Profile Lounge Sofa',    category: 'Living Room', subcategory: 'Sofa Sets',       price: 2200, priceDisplay: 'From $2,200', image: 'img/LR/S10 (1).png',   url: 'living-room.html#sofa-sets' },
  { id: 'sectional-corner-sofa',    name: 'Sectional Corner Sofa',      category: 'Living Room', subcategory: 'Sofa Sets',       price: 3800, priceDisplay: 'From $3,800', image: 'img/LR/S7 (10).webp',  url: 'living-room.html#sofa-sets' },
  { id: 'solid-oak-coffee-table',   name: 'Solid Oak Coffee Table',     category: 'Living Room', subcategory: 'Coffee Tables',   price:  890, priceDisplay: 'From $890',   image: 'IMG/LR/STV.png',       url: 'living-room.html#coffee-tables' },
  { id: 'travertine-coffee-table',  name: 'Travertine Coffee Table',    category: 'Living Room', subcategory: 'Coffee Tables',   price: 1150, priceDisplay: 'From $1,150', image: 'IMG/LR/TTV.png',       url: 'living-room.html#coffee-tables' },
  { id: 'arc-console-table',        name: 'Arc Console Table',          category: 'Living Room', subcategory: 'Console Tables',  price: 1200, priceDisplay: 'From $1,200', image: 'img/T.png',            url: 'living-room.html#console-tables' },
  { id: 'slim-console-table',       name: 'Slim Console Table',         category: 'Living Room', subcategory: 'Console Tables',  price: 1100, priceDisplay: 'From $1,100', image: 'img/s.png',            url: 'living-room.html#console-tables' },
  { id: 'low-console-table',        name: 'Low Console Table',          category: 'Living Room', subcategory: 'Console Tables',  price:  980, priceDisplay: 'From $980',   image: 'img/N.png',            url: 'living-room.html#console-tables' },
  { id: 'teak-side-table',          name: 'Teak Side Table',            category: 'Living Room', subcategory: 'Side Tables',     price:  450, priceDisplay: 'From $450',   image: 'img/G.png',            url: 'living-room.html#side-tables' },
  { id: 'brass-glass-side-table',   name: 'Brass & Glass Side Table',   category: 'Living Room', subcategory: 'Side Tables',     price:  520, priceDisplay: 'From $520',   image: 'img/D1.png',           url: 'living-room.html#side-tables' },
  { id: 'walnut-sideboard',         name: 'Walnut Sideboard',           category: 'Living Room', subcategory: 'Sideboards',      price: 1800, priceDisplay: 'From $1,800', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', url: 'living-room.html#sideboards' },
  { id: 'cane-oak-sideboard',       name: 'Cane & Oak Sideboard',       category: 'Living Room', subcategory: 'Sideboards',      price: 1550, priceDisplay: 'From $1,550', image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80', url: 'living-room.html#sideboards' },
  { id: 'ebony-tv-unit',            name: 'Ebony TV Unit',              category: 'Living Room', subcategory: 'TV Units',        price: 1350, priceDisplay: 'From $1,350', image: 'img/TV Unit.jpg',      url: 'living-room.html#tv-units' },

  /* ─── Dining Room ────────────────────────────────────────── */
  { id: 'rattan-bar-stool',         name: 'Rattan Bar Stool',           category: 'Dining Room', subcategory: 'Bar Stools',      price:  290, priceDisplay: 'From $290',   image: 'img/dinning 2.jpg',    url: 'dining-room.html#bar-stools' },
  { id: 'leather-counter-stool',    name: 'Leather Counter Stool',      category: 'Dining Room', subcategory: 'Bar Stools',      price:  340, priceDisplay: 'From $340',   image: 'img/dinning 3.jpg',    url: 'dining-room.html#bar-stools' },
  { id: 'upholstered-bench',        name: 'Upholstered Bench',          category: 'Dining Room', subcategory: 'Benches',         price:  640, priceDisplay: 'From $640',   image: 'img/dinning 4.jpg',    url: 'dining-room.html#benches' },
  { id: 'leather-dining-chair',     name: 'Leather Dining Chair',       category: 'Dining Room', subcategory: 'Dining Chairs',   price:  380, priceDisplay: 'From $380',   image: 'img/dinning 5.jpg',    url: 'dining-room.html#dining-chairs' },
  { id: 'oak-wishbone-chair',       name: 'Oak Wishbone Chair',         category: 'Dining Room', subcategory: 'Dining Chairs',   price:  320, priceDisplay: 'From $320',   image: 'img/dinning 6.jpg',    url: 'dining-room.html#dining-chairs' },
  { id: 'round-oak-dining-table',   name: 'Round Oak Dining Table',     category: 'Dining Room', subcategory: 'Dining Tables',   price: 2100, priceDisplay: 'From $2,100', image: 'img/dinning 7.jpg',    url: 'dining-room.html#dining-tables' },
  { id: 'extending-walnut-table',   name: 'Extending Walnut Table',     category: 'Dining Room', subcategory: 'Dining Tables',   price: 2450, priceDisplay: 'From $2,450', image: 'img/DINING.jpg',       url: 'dining-room.html#dining-tables' },
  { id: 'walnut-drinks-cabinet',    name: 'Walnut Drinks Cabinet',      category: 'Dining Room', subcategory: 'Drinks Cabinets', price: 1680, priceDisplay: 'From $1,680', image: 'img/dinning 9.jpg',    url: 'dining-room.html#drinks-cabinets' },
  { id: 'ceramic-sideboard',        name: 'Ceramic Sideboard',          category: 'Dining Room', subcategory: 'Sideboards',      price: 1450, priceDisplay: 'From $1,450', image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80', url: 'dining-room.html#sideboards' },

  /* ─── Home Office ────────────────────────────────────────── */
  { id: 'office-desk',              name: 'Office Desk',                category: 'Home Office', subcategory: 'Desks',           price: 1400, priceDisplay: 'From $1,400', image: 'img/H.png',            url: 'home-office.html#desks' },
  { id: 'adjustable-standing-desk', name: 'Adjustable Standing Desk',   category: 'Home Office', subcategory: 'Desks',           price: 1850, priceDisplay: 'From $1,850', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80', url: 'home-office.html#desks' },
  { id: 'floating-shelf-unit',      name: 'Floating Shelf Unit',        category: 'Home Office', subcategory: 'Shelves',         price:  620, priceDisplay: 'From $620',   image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80', url: 'home-office.html#shelves' },
  { id: 'modular-bookshelf',        name: 'Modular Bookshelf',          category: 'Home Office', subcategory: 'Shelves',         price:  980, priceDisplay: 'From $980',   image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80', url: 'home-office.html#shelves' },
  { id: 'brass-desk-lamp',          name: 'Brass Desk Lamp',            category: 'Home Office', subcategory: 'Desk Lamps',      price:  240, priceDisplay: 'From $240',   image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80', url: 'home-office.html#desk-lamps' },

  /* ─── Bedroom ────────────────────────────────────────────── */
  { id: 'platform-bed-frame',       name: 'Platform Bed Frame',         category: 'Bedroom',     subcategory: 'Beds',            price: 1650, priceDisplay: 'From $1,650', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', url: 'bedroom.html#beds' },
  { id: 'linen-upholstered-bed',    name: 'Linen Upholstered Bed',      category: 'Bedroom',     subcategory: 'Beds',            price: 1950, priceDisplay: 'From $1,950', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', url: 'bedroom.html#beds' },
  { id: 'bedside-table',            name: 'Bedside Table',              category: 'Bedroom',     subcategory: 'Bedside Tables',  price:  340, priceDisplay: 'From $340',   image: 'IMG/BD/ss7.png',       url: 'bedroom.html#bedside-tables' },
  { id: 'marble-top-bedside',       name: 'Marble Top Bedside',         category: 'Bedroom',     subcategory: 'Bedside Tables',  price:  420, priceDisplay: 'From $420',   image: 'img/D2.jpg',           url: 'bedroom.html#bedside-tables' },
  { id: 'five-drawer-chest',        name: 'Five-Drawer Chest',          category: 'Bedroom',     subcategory: 'Chest of Drawers',price:  980, priceDisplay: 'From $980',   image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', url: 'bedroom.html#chest-drawers' },
  { id: 'linen-dressing-table',     name: 'Linen Dressing Table',       category: 'Bedroom',     subcategory: 'Dressing Tables', price:  860, priceDisplay: 'From $860',   image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', url: 'bedroom.html#dressing-tables' },
  { id: 'wardrobe',                 name: 'Wardrobe',                   category: 'Bedroom',     subcategory: 'Wardrobes',       price: 2800, priceDisplay: 'From $2,800', image: 'img/Y.png',            url: 'bedroom.html#wardrobes' },
  { id: 'wardrobe-2',               name: 'Wardrobe 2',                 category: 'Bedroom',     subcategory: 'Wardrobes',       price: 3200, priceDisplay: 'From $3,200', image: 'img/Y2.png',           url: 'bedroom.html#wardrobes' },

  /* ─── Shop page aliases (different names used in shop.html) ─ */
  { id: 'linen-cloud-sofa',         name: 'Linen Cloud Sofa',           category: 'Living Room', subcategory: 'Sofa Sets',       price: 2400, priceDisplay: 'From $2,400', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', url: 'living-room.html#sofa-sets' },
  { id: 'marble-console-table',     name: 'Marble Console Table',       category: 'Living Room', subcategory: 'Console Tables',  price: 1200, priceDisplay: 'From $1,200', image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80', url: 'living-room.html#console-tables' },
  { id: 'solid-walnut-desk',        name: 'Solid Walnut Desk',          category: 'Home Office', subcategory: 'Desks',           price: 1400, priceDisplay: 'From $1,400', image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80', url: 'home-office.html#desks' },
  { id: 'oak-wardrobe',             name: 'Oak Wardrobe',               category: 'Bedroom',     subcategory: 'Wardrobes',       price: 2800, priceDisplay: 'From $2,800', image: 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=600&q=80', url: 'bedroom.html#wardrobes' },
  { id: 'chest-of-drawers',         name: 'Chest of Drawers',           category: 'Bedroom',     subcategory: 'Chest of Drawers',price:  980, priceDisplay: 'From $980',   image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', url: 'bedroom.html#chest-drawers' },
];
